### PR TITLE
Fix punycode import error in lib/mail-parser.js

### PR DESCRIPTION
**Pull request by Henri-Leon**
Fix punycode import error in lib/mail-parser.js by removing the trailing slash in the punycode import.

Error that occoured before: "Error: Cannot find module 'punycode/'"

After the correction the error no longer occurs.

### CODE REVIEW

**Comment by andris9** [comment]
Which version of Node.js are you using? The ending slash should work fine

**Comment by andris9** [comment]
Your fix actually breaks things because the slash forces Node to use the Punycode module installed from NPM. Without the slash, Node would use the built-in but deprecated (and soon removed) Punycode module. I wonder, though, why you get the error. Do you run the code as is using `require('mailparser')`, or do you somehow bundle/pre-process it with Babel or Typescript, or use `import` instead of `require` etc?

**Comment by Henri-Leon** [comment]
So i am working on an Obsidian Plugin. 
the workflow uses npm. The depricated soon to be removed module cant be found on my system i think?
I think thats what fixxed it for me then, using the npm version. 

this is the way import the code: `import { simpleParser } from 'mailparser';` in my main.ts file. So i am using Typescript and Obsidian is using Electron i think. 


this is the full error message:  
```
Plugin failure: noti Error: Cannot find module 'punycode/'
Require stack:
- electron/js2c/renderer_init
    at Module._resolveFilename (node:internal/modules/cjs/loader:1084:15)
    at a._resolveFilename (node:electron/js2c/renderer_init:2:2669)
    at Module._load (node:internal/modules/cjs/loader:929:27)
    at c._load (node:electron/js2c/node_init:2:13672)
    at s._load (node:electron/js2c/renderer_init:2:30758)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Ut (app.js:1:268959)
    at o (app.js:1:2243602)
    at node_modules/mailparser/lib/mail-parser.js (plugin:noti:42966:20)
```

**Comment by andris9** [comment]
I used a different module without name collisions and published it as mailparser@3.7.1, please upgrade and try if it works for you.

**Comment by Henri-Leon** [comment]
> I used a different module without name collisions and published it as mailparser@3.7.1, please upgrade and try if it works for you.

i have run `npm install mailparser@3.7.1` and i see it has updated to `const punycode = require('punycode.js');`. It now seems to run without errors. Thanks!

**Pull request closed without merging**
