### PR TITLE
Remove spread operators

### PR DESCRIPTION
**Pull request by alanhoff**
Spread operators are not supported by node yet.

### CODE REVIEW

**Comment by andris9** [comment]
Spread operator is supported by Node.js v6+ which is the current LTS version.

**Comment by farskipper** [comment]
@alanhoff if you need support for older versions of node, check out [this fork](https://github.com/farskipper/mailparser) that removes ES6 sugar and shims modern Buffer APIs so it works on node4 (I needed this b/c AWS Lambda only supports node 4.3 right now)

https://www.npmjs.com/package/mailparser-node4
https://www.npmjs.com/package/mailsplit-node4

**Comment by andris9** [comment]
Lambda added support for Node v6 a week or two ago

**Comment by farskipper** [comment]
Awesome! I missed that announcement. I'll make a note on my fork

**Pull request closed without merging**
